defaults:
  - _self_
  - experiment: STHBC2ViHBC
  - runtime: default

experiment_name: ${hydra:runtime.choices.experiment}
seeds: [0, 10, 2026, 2027, 3407]

hydra:
  run:
    dir: new_outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
