defaults:
  - base
  - _self_

split_mode: loo
all_names: ['CRC_A1', 'CRC_A2', 'CRC_B1', 'CRC_B2', 'CRC_C1', 'CRC_C2', 'CRC_D1', 'CRC_D2', 'CRC_E1', 'CRC_E2', 'CRC_G1', 'CRC_G2',]
data_dir: '../../../../processed_data/CRC'
k_neighbors: 6
num_workers: 3

