defaults:
  - base
  - _self_

split_mode: fixed
ref_names: ['A1', 'B1', 'C1', 'D1', 'E1', 'F1', 'G2', 'H1']
tgt_names: ['ViHBC1', 'ViHBC2', 'ViHBC3']
data_dir: '../../../../processed_data/STHBC2ViHBC'
k_neighbors: 8
num_workers: 3
