defaults:
  - base
  - _self_

training:
  batch_size: 2048
  dropout: 0.5
  cls_dropout: 0.5
  gene_mask: 0.5
  patch_mask: 0.5

teacher:
  training:
    epochs: 100
    warm_up_epoch: 30
    optimizer:
      lr: 5e-5
      weight_decay: 4e-4


student:
  training:
    epochs: 100
    warm_up_epoch: 0
    optimizer:
      lr: 5e-5
      weight_decay: 4e-4

    dropout: 0.8
    cls_dropout: 0.8
    patch_mask: 0.8